### ISSUE TITLE
Omitting the src attribute

### ISSUE THREAD

**Issue by tyssen** [nbcommunication/PageimageSource#6]
I use [LazySizes](https://github.com/aFarkas/lazysizes) for lazyloading and one of the recommended implementations is to either leave out the `src` attribute altogether (instead use `data-src`) or use a data URI for a blank gif instead.

But when I'm using this module, if I have something like this:

    return $img->render('<img
      class="lazyload '.$classes.'"
      src="{url}"
      data-sizes="auto"
      decoding="async"
      width="'.$width.'"
      height="'.$height.'"
    >',
    [
      'srcset' => $sizes,
      'lazy' => false
    ]);

if I don't include `src="{url}"` then my custom HTML won't render, it will just output default `<img>` markup.

So in this case, I still want it to output the `<picture>` markup with webp and jpeg versions, but I'd like the markup for `<img>` to not have the `src` attribute.

Would that be possible to add to the module?

**Comment by chriswthomson** [comment]
Hi @tyssen,

I don't think it is within the scope of this module to do this. The `src` attribute is required for the `<img>` tag, and I assume this doesn't change when used inside a `<picture>` element.

However, this bit of code should do what you need to do, pop it in site/ready.php

```php
$wire->addHookAfter('Pageimage::render', function(HookEvent $event) {
	if(strpos($event->return, '<picture') !== false) {
		$event->return = str_replace('<img src=', '<img data-src=', $event->return);
	}
});
```

You will need to put the `src` attribute first however.

Cheers,

Chris

**Comment by tyssen** [comment]
Thanks, that will work. I changed it to:

    $event->return = str_replace('<img src=', '<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src=', $event->return);
